"""
scaffold.py -- generate a harness stub for a READY target (TDD section 4.5).

This closes the loop back to Engine A: once the interrogation gate says a target
is READY, we emit a Verdict-Engine harness stub the user drops into their repo --
a SymptomSpec + plugin skeleton + a golden-fixture stub, all wired against the
Phase-1 contracts in verdict_engine.py.

LOAD-BEARING RULE (the moat): we generate ONLY for a target whose gate status is
READY. Refusing to generate where the eval would be theater is the whole product;
scaffolding is the reward for passing the gate, never the default. generate() raises
if handed a non-READY GateResult.

Pure stdlib string templating. No LLM. The output is code, but it is emitted by a
deterministic function off a validated verdict -- not proposed by a model.
"""
from __future__ import annotations

import re

from readiness_gate import GateResult, Status


def _slug(name: str) -> str:
    """A python-identifier-safe slug from a human target name."""
    s = re.sub(r"[^0-9a-zA-Z]+", "_", name.strip().lower()).strip("_")
    if not s:
        s = "target"
    if s[0].isdigit():
        s = "t_" + s
    return s


class ScaffoldError(RuntimeError):
    """Raised when scaffolding is requested for a non-READY target."""


def generate(result: GateResult) -> dict:
    """Return {filename: file_contents} for a READY target. Raise otherwise.

    Emits three files, matching the shapes of the built, validated example
    (recall_oracle.py + golden_fixtures.py):
      - <slug>_oracle.py    : SymptomSpec + evaluate_attempt() plugin skeleton
      - <slug>_fixtures.py   : a golden-fixture stub (EvidenceBundle + expected)
      - <slug>_runner.py     : an attempt-loop + positive-control skeleton
    """
    if result.status != Status.READY:
        raise ScaffoldError(
            f"refusing to scaffold {result.target!r}: status is {result.status.value}, "
            f"not READY. The gate withholds generation until an honest eval is possible "
            f"(blocked_on: {result.blocked_on or 'n/a'})."
        )

    slug = _slug(result.target)
    header = (f'"""AUTO-GENERATED harness stub for target: {result.target}\n'
              f'oracle_class: {result.oracle_class.value}\n'
              f'Generated by Oraculum because the readiness gate marked this READY.\n'
              f'Fill in the TODOs: wire your real signal source, then hand-label fixtures."""')

    return {
        f"{slug}_oracle.py": _oracle_stub(slug, result, header),
        f"{slug}_fixtures.py": _fixtures_stub(slug, result, header),
        f"{slug}_runner.py": _runner_stub(slug, result, header),
    }


def _oracle_stub(slug: str, result: GateResult, header: str) -> str:
    cls = _slug_camel(slug)
    return f'''{header}
from dataclasses import dataclass

from verdict_engine import Attempt


@dataclass
class {cls}Symptom:
    """A machine-checkable symptom for: {result.target}
    TODO: replace these fields with the machine-checkable predicate for your signal.
    """
    # e.g. an expected value, a regex, a threshold, an id that must appear...
    expected: str = ""          # TODO: define what "the symptom occurred" means
    # TODO: add the observable identifier(s) your signal source produces


def evaluate_attempt(attempt_id: str,
                     raw_signals: dict,
                     symptom: {cls}Symptom,
                     observed: bool = True,
                     env: str = "default") -> Attempt:
    """Oracle: one raw signal capture -> a structured Attempt (plugins observe;
    the spine judges). observed=False models a crash/timeout BEFORE the
    observation point => attempt_valid=False ("couldn't look", not "absent").
    """
    if not observed:
        return Attempt(attempt_id=attempt_id, attempt_valid=False,
                       hit=False, env_fingerprint=env)

    # TODO: compute `hit` from raw_signals + symptom. This is the ONE predicate
    # you must write for your domain. Everything else is reused from the spine.
    hit = False  # TODO: e.g. raw_signals.get("value") == symptom.expected
    return Attempt(attempt_id=attempt_id, attempt_valid=True,
                   hit=hit, env_fingerprint=env)
'''


def _fixtures_stub(slug: str, result: GateResult, header: str) -> str:
    return f'''{header}
from verdict_engine import (
    EvidenceBundle, Attempt, PositiveControl, PCStatus, Verdict, SubState,
)


def make_attempts(n_valid, n_hits, n_invalid=0, env="default"):
    atts = [Attempt(f"v{{i}}", True, True, env) for i in range(n_hits)]
    atts += [Attempt(f"m{{i}}", True, False, env) for i in range(n_valid - n_hits)]
    atts += [Attempt(f"x{{i}}", False, False, env) for i in range(n_invalid)]
    return atts


# each entry: (name, bundle, expected_verdict, expected_sub_state)
# TODO: hand-label these with KNOWN-correct verdicts for "{result.target}".
# They become this harness's own regression guard (render(fixture) == expected).
GOLDEN = [
    ("stable_repro_stub",
     EvidenceBundle("r1", "{slug}", make_attempts(6, 6)),
     Verdict.CONFIRMED_REPRO, SubState.STABLE),
    ("not_repro_stub",
     EvidenceBundle("r2", "{slug}", make_attempts(228, 0), PositiveControl(PCStatus.PASS)),
     Verdict.CONFIRMED_NOT_REPRO, None),
    # TODO: add a FLAKY case and an INCONCLUSIVE case once your signal is wired.
]
'''


def _runner_stub(slug: str, result: GateResult, header: str) -> str:
    cls = _slug_camel(slug)
    return f'''{header}
from verdict_engine import EvidenceBundle, PositiveControl, PCStatus, render, Thresholds
from {slug}_oracle import {cls}Symptom, evaluate_attempt


def run_attempts(symptom: {cls}Symptom, s: int, env: str = "default") -> EvidenceBundle:
    """Skeleton stress loop: capture a signal S times -> Attempt[] -> EvidenceBundle.
    TODO: replace `capture_signal_once()` with your real driver (the ActionLayer).
    """
    attempts = []
    for i in range(s):
        raw = capture_signal_once()          # TODO: run your case, capture signals
        observed = raw is not None           # None => couldn't observe this attempt
        attempts.append(
            evaluate_attempt(f"a{{i}}", raw or {{}}, symptom, observed=observed, env=env))
    # TODO: run a positive control -- inject a KNOWN instance of the symptom and
    # confirm the harness catches it. Without it, no NOT_REPRO verdict is valid.
    pc = PositiveControl(PCStatus.NOT_RUN)   # TODO: set PASS/FAIL from your control run
    return EvidenceBundle("run-1", "{slug}", attempts, pc)


def capture_signal_once():
    """TODO: run one repro attempt and return the raw signals dict (or None if the
    attempt crashed/timed out before the observation point)."""
    raise NotImplementedError("wire your signal source here")


if __name__ == "__main__":
    # Once capture_signal_once() is implemented:
    #   bundle = run_attempts({cls}Symptom(expected="..."), s=50)
    #   print(render(bundle, Thresholds()))
    print("Fill in capture_signal_once() and the SymptomSpec, then render(bundle).")
'''


def _slug_camel(slug: str) -> str:
    return "".join(part.capitalize() for part in slug.split("_")) or "Target"
